name: surgatani
description: "Aplikasi Survei Harga Pertanian"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Sebaiknya gunakan rentang yang lebih luas

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Utilities
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # State Management
  provider: ^6.1.2

  # Local Storage / Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0

  # Fitur Tambahan
  image_picker: ^1.1.2
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Versi umum, sesuaikan jika perlu

  # Alat bantu development
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  
  # --- PINDAHKAN KE SINI ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_surgatani.png"
